FROM nginx:1.17.10
ARG WEB_CONF
ARG WEB_TEMPLATE

# RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./${WEB_TEMPLATE} /etc/nginx/conf.d/${WEB_TEMPLATE}
COPY ./${WEB_CONF} /etc/nginx/nginx.conf
ADD ./public /etc/nginx/www

ENV DOLLAR $

CMD /bin/bash -c "envsubst  '\$PORT \$APP_BACKEND_PORT \$DOLLAR \$APP_UPLOAD_MAXSIZE' < /etc/nginx/conf.d/${WEB_TEMPLATE} > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
