FROM nginx:1.17.4

RUN rm /etc/nginx/conf.d/default.conf
COPY ./${WEB_TEMPLATE} /etc/nginx/conf.d/${WEB_TEMPLATE}
COPY ./${WEB_CONF} /etc/nginx/nginx.conf
ENV DOLLAR $

CMD ["/bin/bash", "-c", "envsubst < /etc/nginx/conf.d/${WEB_TEMPLATE} > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
